version: '3.8'

networks:
    app-network:
        driver: bridge


services:
    webserver:
        image: nginx:1.21.6-alpine
        container_name: webserver
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - .docker/nginx:/etc/nginx/conf.d
        networks:
            - app-network

    database:
        image: mysql:8.0
        container_name: database
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: aqarmap
            MYSQL_ROOT_PASSWORD: password
            MYSQL_PASSWORD: password
            MYSQL_USER: aqarmap
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - .docker/mysql:/docker-entrypoint-initdb.d
        networks:
            - app-network
    backend:
        build:
            context: .docker/php
            dockerfile: Dockerfile
        container_name: backend
        volumes:
            - ./:/var/www
            - .docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network
